#!/usr/bin/env php
<?php

// Use Composer's global autoloader
require __DIR__ . '/../../autoload.php';

use PocketFrame\Commands\NewCommand;
use Symfony\Component\Console\Application;

$app = new Application('PocketFrame Installer', '1.0.0');
$app->add(new NewCommand());
$app->run();
